name: scipy16
channels:
        - conda-forge
dependencies:
        - numpy
        - pandas
        - matplotlib
        - jupyter
        - seaborn
        - pip
        - geopandas
        - pysal
        - cartopy
        - pyproj
        - shapely
        - geopy
        - scikit-learn

